apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  db_host: {{ .Values.db_host | b64encode }}
  db_name: {{ .Values.db_name | b64encode }}
  db_user: {{ .Values.db_user | b64encode }}
  db_password: {{ .Values.db_password | b64encode }}
