name: Deploy to Minikube

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"
    
    - name: Set up Terraform
      run: |
        sudo apt-get update -y
        sudo apt-get install -y terraform
    
    - name: Terraform Init
      run: terraform -chdir=./terraform init -backend-config="region=us-east-1" -backend-config="dynamodb_table=${{ secrets.DYNAMODB_TABLE }}"
    
    - name: Terraform Apply
      run: terraform -chdir=./terraform apply -var "db_name=${{ secrets.DB_NAME }}" -var "db_username=${{ secrets.DB_USERNAME }}" -var "db_password=${{ secrets.DB_PASSWORD }}" -auto-approve
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/secret.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
    
    - name: Minikube ingress
      run: kubectl expose deployment sample-app --type=LoadBalancer --name=sample-app-service --port=80 --target-port=5000
    
    - name: Test Application Health
      run: |
        echo "Checking application health..."
        curl -s http://localhost:5000/health
